openapi: "3.0.0"
info:
  version: 1.0.0
  title: Lifelong Learner
  description: TODO
servers:
  - url: https://{hostname}/api
    variables:
      hostname:
        default: localhost
paths:
  /users/current:
    get:
      operationId: getCurrentUser
      responses:
        "200":
          description: todo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      required:
        - displayName
        - balance
        - role
      properties:
        displayName:
          type: string
        balance:
          type: integer
        role:
          type: string

    Error:
      type: object
      required:
        - slug
        - message
      properties:
        slug:
          type: string
        message:
          type: string
