// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/4RSTW/bMAz9KwO3o1Fn2023fWNDsR7WYYeiB0ZmbBWypJF0gSDwfx8oJVmHBejJND8e",
	"33viAXyeS06UVMAdQPxEM9bwE3NmCwrnQqyBanomERzJQt0XAgeiHNIIawcSl/FCYe2A6fcSmAZwd62r",
	"OwPdd6f+vH0grwb0U+jC6i1GTP7p6pCURmIbGYKUiPvvOF/mxjnS89yeonTnhcfp/5maZvILB93/MOca",
	"z/eETPxu0amyrn+fM8+o4ODbr1voms+G1KpwRp5UC6wGHNIu2/xA4jkUDTmBg9ubjzfWHdTkwHXYUcxp",
	"fHFNyKkCPRJL6319tbnamPZcKGEJ4OBtTXVQUKfKtV+EWHq/MFNSy4xUP2Y82tKvAzj4QvqhtdSnMdOk",
	"5CRN8JvNxj4+Jz2CYCkx+DrfP4ixOd2WRa+YduDgZf/3+Prj5fUVvxrwr3DNQ7Z885xNJbi7Aywcj7aJ",
	"6/vDlEUTzrT2JriDR+SA29h4norN1h0u0V4kZo/RSgZ/v/4JAAD//2X/B7gTAwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
